### ISSUE TITLE
[ie9,html4] onloadend not fired

### ISSUE THREAD

**Issue by jackd0ng** [moxiecode/moxie#135]
when using xhr 2 to upload file (ie 9,html 4 runtime), the onloadend event was not fired;
and if  not change the file selected and upload it again,the onloadend event was fired correctly 
(but the json response was not handled)

**Comment by jayarjo** [comment]
There was a regression that caused Plupload to fail in IE9 in general. That has been fixed now, try the latest release. Otherwise `loadend` seems to be firing properly.

**Comment by jackd0ng** [comment]
Thanks a lot for your reply :)
i tried the moxie-1.3.3 (the latest,right?),but it is not fixed.

the ie9 ->
version: 9.0.8112.16421
update version:9.0.39 (KB3058515)

the code->
function bindUploadAction(filePicker, fileUploader, progress){

	var fileInput = new mOxie.FileInput({
		browse_button: filePicker,
		accept:[
			{title: "Images", extensions: "jpg,jpeg,png,gif"}
		]
	});

	fileInput.onchange = function (e){
		var file = e.target.files[0];
		$("#" + progress).text(file.name);
	};

	fileInput.init();


	$("#" + fileUploader).click(function uploadImage(){
		if(!fileInput.files || fileInput.files.length === 0){
			alert("Please select a file!");
			return;
		}

		var xhr = new mOxie.XMLHttpRequest();
		xhr.open('POST', getUrl(), true);
		xhr.onloadend = function(e){
			console.log("onloadend");
			console.log(e.target.response);
		};

		var formData = new mOxie.FormData();
		formData.append("file", fileInput.files[0]);

		xhr.send(formData);
	});

	function getUrl(){
		return 'dummy';
	}
}

**Comment by jayarjo** [comment]
To initialise `html4` runtime you need to set `runtime_order` to `html4`:

```javascript
var fileInput = new mOxie.FileInput({
        browse_button: filePicker,
        runtime_order: 'html4',
        accept: [
            {title: "Images", extensions: "jpg,jpeg,png,gif"}
        ]
});
```

Try `alert` instead of `console.log` as the latter is not supported in IE9. Otherwise your code seems ok and `onloadend` should work.

**Comment by jackd0ng** [comment]
i was debugging by using moxie.js , and sure that the runtime was html4 (from the log or the runtime html tag with class "moxie-shim-html4");

i replaced <code>console.log</code> with  <code>alert</code>, and it still not worked.

there is something suspicious:
<strong>HTML1113: Document mode restart from IE9 Standards to Quirks</strong>
(maybe this is the target problem?)

response header->
Response HTTP/1.1 200 OK
Date	Fri, 10 Jul 2015 02:59:03 GMT
Server	Apache
Cache-Control	max-age=0
Expires	Fri, 10 Jul 2015 02:59:03 GMT
Content-Type	application/json;charset=GBK
Keep-Alive	timeout=5, max=100
Connection	Keep-Alive

**Comment by jayarjo** [comment]
Are you testing it in real IE9 or emulating it? Emulators do not always reflect the real experience. We run our unit tests on actual browsers and they all complete successfully, including those that test events in `html4` runtime.

But I tested your case specifically, with your code. The only thing that I replaced was `console.log` and it worked, so it should be something specific to your environment. Are you maybe missing a doctype at the top of your html document?

**Comment by jackd0ng** [comment]
i am testing it in real IE9 ,but it is win7 OS.

i am not missing a doctype at the top of my html document.
<code>HTML1113</code> logged out when the JSON response was filled into  iframe with name as like "uid_19pr526le1jrb19q8pcd1o293r56_iframe";

agree with you, and it must be something specific to my environment.
which version of IE9 and Windows are you using?

Thanks

**Comment by jayarjo** [comment]
I tested on IE9/Win7 and IE8/XP. Both did fire `onloadend`. Can you maybe put a full example somewhere online?

**Comment by jackd0ng** [comment]
sorry, i can not give a full example online now (maybe days later).

when i changed the response content-type to 
<code>Content-Type	application/xml;charset=utf-8</code>,
the onloadend was fired properly.

in the case you tested , the response content-type is json,right?

**Comment by jayarjo** [comment]
What header were you sending previously?

**Comment by jackd0ng** [comment]
Previously, the response was json with header as <code>application/json</code>.
And there was the problem.

Now,the response is empty with header as <code>application/xml</code>. 
And it worked fine.

**Comment by jayarjo** [comment]
`application/json` causes download for the json response in legacy browsers, so do not use it. You can close the ticket if you managed to solve the issue.
